# Generated by Django 5.2.8 on 2025-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.IntegerField(null=True)),
                ('word_count', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('title_length', models.IntegerField(null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_description_length', models.IntegerField(null=True)),
                ('h1_count', models.IntegerField(null=True)),
                ('h2_count', models.IntegerField(null=True)),
                ('h3_count', models.IntegerField(null=True)),
                ('internal_links', models.TextField(null=True)),
                ('external_links', models.TextField(null=True)),
                ('images_count', models.IntegerField(null=True)),
                ('images_with_alt', models.IntegerField(null=True)),
                ('top_keywords', models.TextField(null=True)),
                ('seo_score', models.IntegerField(null=True)),
            ],
        ),
    ]
