# Generated by Django 5.2.8 on 2025-12-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeoProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdetails',
            name='http_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='is_secure',
            field=models.BooleanField(null=True),
        ),
    ]
