# Generated by Django 6.0 on 2026-01-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeoProjectApp', '0002_auditdetails_http_status_auditdetails_is_secure'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdetails',
            name='data_audit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='desktop_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='h4_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='h5_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='h6_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='images_lazy_loading',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='images_seo_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='links_seo_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='meta_seo_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='mobile_score',
            field=models.IntegerField(null=True),
        ),
    ]
