# Generated by Django 6.0 on 2026-01-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeoProjectApp', '0003_auditdetails_data_audit_auditdetails_desktop_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdetails',
            old_name='data_audit',
            new_name='date_audit',
        ),
    ]
