# Generated by Django 6.0 on 2026-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeoProjectApp', '0004_rename_data_audit_auditdetails_date_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdetails',
            name='nombre_paragraphes',
            field=models.IntegerField(null=True),
        ),
    ]
